/*
 * bsp.h
 *
 *  Created on: May 13, 2025
 *      Author: rumbl
 */

#ifndef BSP_H_
#define BSP_H_

#include "stm32f1xx.h"

#define BSP_RGB_RED_LED_GPIO_PIN 4u
#define BSP_RGB_RED_LED_GPIO_PORT GPIOB

#define BSP_RGB_GREEN_LED_GPIO_PIN 5u
#define BSP_RGB_GREEN_LED_GPIO_PORT GPIOB

#define BSP_RGB_BLUE_LED_GPIO_PIN 3u
#define BSP_RGB_BLUE_LED_GPIO_PORT GPIOB

#define BSP_SDC_SPI_MOSI_PIN 7u
#define BSP_SDC_SPI_MOSI_PORT GPIOA

#define BSP_SDC_SPI_MISO_PIN 6u
#define BSP_SDC_SPI_MISO_PORT GPIOA

#define BSP_SDC_SPI_SCLK_PIN 5u
#define BSP_SDC_SPI_SCLK_PORT GPIOA

#define BSP_SDC_SPI_CS_PIN 4u
#define BSP_SDC_SPI_CS_PORT GPIOA

#define BSP_SDC_SPI SPI1

#define BSP_CH1_UART USART3
#define BSP_CH1_UART_TX_PORT GPIOB
#define BSP_CH1_UART_TX_PIN 10u
#define BSP_CH1_UART_RX_PORT GPIOB
#define BSP_CH1_UART_RX_PIN 11u
#define BSP_CH1_EN_PORT GPIOB
#define BSP_CH1_EN_PIN 0u

#define BSP_CH2_UART USART2
#define BSP_CH2_UART_TX_PORT GPIOA
#define BSP_CH2_UART_TX_PIN 2u
#define BSP_CH2_UART_RX_PORT GPIOA
#define BSP_CH2_UART_RX_PIN 3u
#define BSP_CH2_EN_PORT GPIOB
#define BSP_CH2_EN_PIN 1u

#define BSP_CH3_UART USART1
#define BSP_CH3_UART_TX_PORT GPIOB
#define BSP_CH3_UART_TX_PIN 6u
#define BSP_CH3_UART_RX_PORT GPIOB
#define BSP_CH3_UART_RX_PIN 7u
#define BSP_CH3_EN_PORT GPIOB
#define BSP_CH3_EN_PIN 2u


#endif /* BSP_H_ */
